//go:build riscv64

package mojette

import "golang.org/x/sys/cpu"

// xorRVV folds the whole region (min of the two lengths) of src into dst
// (dst ^= src) with the RISC-V vector extension and returns the byte count
// consumed. The kernel is length-agnostic (VSETVLI per strip). Generated by
// go-asmgen (mojette_xor_riscv64_gen.go) into mojette_xor_riscv64.s.
func xorRVV(dst, src []byte) (done int)

// hasV reports whether the V (vector) extension is present; the V instructions
// trap on a hart without it, so the kernel is only dispatched when true.
var hasV = cpu.RISCV64.HasV

// xorBlock XORs src into dst byte-wise. With V present the RVV kernel folds the
// whole region (any length) and the scalar tail is empty; without V the scalar
// loop does all the work.
func xorBlock(dst, src []byte) {
	done := 0
	if hasV {
		done = xorRVV(dst, src)
	}
	xorBlockScalar(dst[done:], src[done:])
}
