//go:build arm64

package mojette

// xorNEON folds whole 16-byte blocks of src into dst (dst ^= src) with the NEON
// VEOR and returns the number of bytes consumed (a multiple of 16). NEON is the
// arm64 baseline, so there is no runtime feature check. Generated by go-asmgen
// (mojette_xor_arm64_gen.go) into mojette_xor_arm64.s.
func xorNEON(dst, src []byte) (done int)

const blockNEON = 16

// xorBlock XORs src into dst byte-wise with the NEON kernel over whole 16-byte
// blocks, finishing the 0..15-byte tail with the scalar loop.
func xorBlock(dst, src []byte) {
	n := len(dst)
	if len(src) < n {
		n = len(src)
	}
	done := 0
	if n >= blockNEON {
		done = xorNEON(dst, src)
	}
	xorBlockScalar(dst[done:], src[done:])
}
