// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·xorVSX(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R3
	MOVD dst_len+8(FP), R4
	MOVD src_base+24(FP), R5
	MOVD src_len+32(FP), R6
	CMP R6, R4
	BGE usedst
	MOVD R6, R4
usedst:
	SRD $4, R4, R9
	MOVD $0, R10
loop:
	CMP R9, $0
	BEQ done
	ADD R5, R10, R12
	ADD R3, R10, R15
	LXVD2X (R15)(R0), VS32
	LXVD2X (R12)(R0), VS33
	VXOR V0, V1, V2
	STXVD2X VS34, (R15)(R0)
	ADD $16, R10, R10
	ADD $-1, R9, R9
	BR loop
done:
	MOVD R10, done+48(FP)
	RET

