// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·xorSSE2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ dst_len+8(FP), CX
	MOVQ src_base+24(FP), SI
	MOVQ src_len+32(FP), AX
	CMPQ AX, CX
	CMOVQLT AX, CX
	MOVQ CX, R8
	SHRQ $4, R8
	XORQ R9, R9
	TESTQ R8, R8
	JZ done
loop:
	MOVOU (DI)(R9*1), X0
	MOVOU (SI)(R9*1), X1
	PXOR X1, X0
	MOVOU X0, (DI)(R9*1)
	ADDQ $16, R9
	DECQ R8
	JNZ loop
done:
	MOVQ R9, done+48(FP)
	RET

TEXT ·xorAVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ dst_len+8(FP), CX
	MOVQ src_base+24(FP), SI
	MOVQ src_len+32(FP), AX
	CMPQ AX, CX
	CMOVQLT AX, CX
	MOVQ CX, R8
	SHRQ $5, R8
	XORQ R9, R9
	TESTQ R8, R8
	JZ done
loop:
	VMOVDQU (DI)(R9*1), Y0
	VMOVDQU (SI)(R9*1), Y1
	VPXOR Y1, Y0, Y0
	VMOVDQU Y0, (DI)(R9*1)
	ADDQ $32, R9
	DECQ R8
	JNZ loop
done:
	VZEROUPPER
	MOVQ R9, done+48(FP)
	RET

