// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·xorRVV(SB), NOSPLIT, $0-56
	MOV dst_base+0(FP), X5
	MOV dst_len+8(FP), X6
	MOV src_base+24(FP), X7
	MOV src_len+32(FP), X8
	BGE X6, X8, usesrc
	JMP haveN
usesrc:
	MOV X8, X6
haveN:
	MOV $0, X10
loop:
	BEQZ X6, done
	VSETVLI X6, E8, M1, TA, MA, X9
	VLE8V (X5), V0
	VLE8V (X7), V1
	VXORVV V1, V0, V0
	VSE8V V0, (X5)
	ADD X9, X5, X5
	ADD X9, X7, X7
	SUB X9, X6, X6
	ADD X9, X10, X10
	JMP loop
done:
	MOV X10, done+48(FP)
	RET

