//go:build s390x

package mojette

// xorVX folds whole 16-byte blocks of src into dst (dst ^= src) with the z/Arch
// vector-facility VX and returns the number of bytes consumed (a multiple of
// 16). The vector facility (z13) is the s390x baseline, so there is no runtime
// feature check. Generated by go-asmgen (mojette_xor_s390x_gen.go) into
// mojette_xor_s390x.s.
func xorVX(dst, src []byte) (done int)

const blockVX = 16

// xorBlock XORs src into dst byte-wise with the vector kernel over whole 16-byte
// blocks, finishing the 0..15-byte tail with the scalar loop.
func xorBlock(dst, src []byte) {
	n := len(dst)
	if len(src) < n {
		n = len(src)
	}
	done := 0
	if n >= blockVX {
		done = xorVX(dst, src)
	}
	xorBlockScalar(dst[done:], src[done:])
}
