// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·xorLSX(SB), NOSPLIT, $0-56
	MOVV dst_base+0(FP), R4
	MOVV dst_len+8(FP), R5
	MOVV src_base+24(FP), R6
	MOVV src_len+32(FP), R7
	BLT R7, R5, usesrc
	JMP haveN
usesrc:
	MOVV R7, R5
haveN:
	SRLV $4, R5, R10
	MOVV $0, R11
loop:
	BEQ R10, R0, done
	ADDV R6, R11, R13
	ADDV R4, R11, R15
	VMOVQ (R15), V0
	VMOVQ (R13), V1
	VXORV V1, V0, V0
	VMOVQ V0, (R15)
	ADDV $16, R11, R11
	ADDV $-1, R10, R10
	JMP loop
done:
	MOVV R11, done+48(FP)
	RET

