//go:build loong64

package mojette

// xorLSX folds whole 16-byte blocks of src into dst (dst ^= src) with the LSX
// VXORV and returns the number of bytes consumed (a multiple of 16). LSX is
// treated as the loong64 baseline (as in the sibling go-simd packages), so there
// is no runtime feature check. Generated by go-asmgen (mojette_xor_loong64_gen.go)
// into mojette_xor_loong64.s.
func xorLSX(dst, src []byte) (done int)

const blockLSX = 16

// xorBlock XORs src into dst byte-wise with the LSX kernel over whole 16-byte
// blocks, finishing the 0..15-byte tail with the scalar loop.
func xorBlock(dst, src []byte) {
	n := len(dst)
	if len(src) < n {
		n = len(src)
	}
	done := 0
	if n >= blockLSX {
		done = xorLSX(dst, src)
	}
	xorBlockScalar(dst[done:], src[done:])
}
