// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·xorVX(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R1
	MOVD dst_len+8(FP), R2
	MOVD src_base+24(FP), R3
	MOVD src_len+32(FP), R4
	CMPBLE R2, R4, haveN
	MOVD R4, R2
haveN:
	SRD $4, R2, R7
	MOVD $0, R8
loop:
	CMPBEQ R7, $0, done
	ADD R3, R8, R11
	ADD R1, R8, R12
	VL (R12), V0
	VL (R11), V1
	VX V1, V0, V2
	VST V2, (R12)
	ADD $16, R8, R8
	ADD $-1, R7, R7
	BR loop
done:
	MOVD R8, done+48(FP)
	RET

