//go:build amd64

package mojette

import "golang.org/x/sys/cpu"

// xorSSE2 folds whole 16-byte blocks of src into dst (dst ^= src) with PXOR;
// xorAVX2 does the same over whole 32-byte blocks with VPXOR. Both return the
// number of bytes consumed (a whole multiple of their block width). Generated by
// go-asmgen (mojette_xor_amd64_gen.go) into mojette_xor_amd64.s.
func xorSSE2(dst, src []byte) (done int)
func xorAVX2(dst, src []byte) (done int)

// hasAVX2 gates the wider kernel; SSE2 is the amd64 baseline and always present.
var hasAVX2 = cpu.X86.HasAVX2

const (
	blockSSE2 = 16
	blockAVX2 = 32
)

// xorBlock XORs src into dst byte-wise via the widest applicable kernel (AVX2 if
// the CPU has it and there is a whole 32-byte block, else SSE2 for a whole
// 16-byte block), finishing the remaining tail with the scalar loop.
func xorBlock(dst, src []byte) {
	n := len(dst)
	if len(src) < n {
		n = len(src)
	}
	done := 0
	switch {
	case hasAVX2 && n >= blockAVX2:
		done = xorAVX2(dst, src)
	case n >= blockSSE2:
		done = xorSSE2(dst, src)
	}
	xorBlockScalar(dst[done:], src[done:])
}
