//go:build ppc64le

package mojette

// xorVSX folds whole 16-byte blocks of src into dst (dst ^= src) with the VSX
// VXOR and returns the number of bytes consumed (a multiple of 16). It uses only
// POWER8 (ISA 2.07) baseline instructions (LXVD2X/STXVD2X/VXOR), so there is no
// runtime feature check and no SIGILL on POWER8. Generated by go-asmgen
// (mojette_xor_ppc64le_gen.go) into mojette_xor_ppc64le.s.
func xorVSX(dst, src []byte) (done int)

const blockVSX = 16

// xorBlock XORs src into dst byte-wise with the VSX kernel over whole 16-byte
// blocks, finishing the 0..15-byte tail with the scalar loop.
func xorBlock(dst, src []byte) {
	n := len(dst)
	if len(src) < n {
		n = len(src)
	}
	done := 0
	if n >= blockVSX {
		done = xorVSX(dst, src)
	}
	xorBlockScalar(dst[done:], src[done:])
}
