// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·xorNEON(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD dst_len+8(FP), R1
	MOVD src_base+24(FP), R2
	MOVD src_len+32(FP), R3
	CMP R3, R1
	CSEL LT, R1, R3, R1
	LSR $4, R1, R6
	MOVD $0, R7
loop:
	CBZ R6, done
	ADD R0, R7, R10
	ADD R2, R7, R9
	VLD1 (R10), [V0.B16]
	VLD1 (R9), [V1.B16]
	VEOR V1.B16, V0.B16, V0.B16
	VST1 [V0.B16], (R10)
	ADD $16, R7, R7
	SUB $1, R6, R6
	JMP loop
done:
	MOVD R7, done+48(FP)
	RET

